### ISSUE TITLE
stderredlib snippet outdated and broken

### ISSUE THREAD

**Issue by ssbarnea** [cehoffman/dotfiles#3]
Apparently the code from https://github.com/cehoffman/dotfiles/blob/master/zsh/config#L167 is outdated and it does not really work on latest MacOS with zsh.

There is no stderred formula and the expected location is empty but I was able to manually clone stderred, run `make universal && make install` and I ended up with the libary inside `/usr/local/lib/libstderred.dylib`

I did update the snippet to make it load but surprise, no error and no coloring.

Funny part is that the fallback to use colorize partially works, the only issue with it is that it is that is breaks if the application has interactive prompts outputing on stderr, and in this case is gets ugly because execution stops without use being able to see what happens. You can see full details at https://github.com/sickill/stderred/issues/60

If you have any idea on how to fix this it would be great because having stderr using a different color is a big productivity booster.

**Comment by cehoffman** [comment]
It isn't broken, but it isn't very accommodating to the default Homebrew install. I have homebre installed at `~/.homebrew`, so a stderred install targeting homebrew management will have a file there. To make it more generic, it could or should really be using `brew --prefix` to find the right root location.

**Comment by ssbarnea** [comment]
@cehoffman Indeed, I corrected it with me more generic version. Still, I am curious if you are using zsh+stderr and if so, on which MacOS version. Apparently it no longer works with recent versions of MacOS due to having the code not signed (no error visible but the library is not loaded).

**Comment by cehoffman** [comment]
I do use it, but I have it off more often than not due to issue with golang executables not working (failing to start) with it due to them not using the standard C library for IO.

Here is a picture showing it. 
![image](https://user-images.githubusercontent.com/27545/42775967-596a1626-88fb-11e8-8432-7cd7564ee4b5.png)

The red from git here is printed through stderr and colored by stderred.

**Comment by ssbarnea** [comment]
@cehoffman thanks! Maybe i will look a little bit more on it to see what happens once I have some time (liked over the weekend).
